//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtualizadorMatriculas.FluigColleagueService {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.foundation.ecm.technology.totvs.com/")]
    public partial class Exception : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.foundation.ecm.technology.totvs.com/")]
    public partial class colleagueDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activeField;
        
        private bool activeFieldSpecified;
        
        private bool adminUserField;
        
        private bool adminUserFieldSpecified;
        
        private int area1IdField;
        
        private bool area1IdFieldSpecified;
        
        private int area2IdField;
        
        private bool area2IdFieldSpecified;
        
        private int area3IdField;
        
        private bool area3IdFieldSpecified;
        
        private int area4IdField;
        
        private bool area4IdFieldSpecified;
        
        private int area5IdField;
        
        private bool area5IdFieldSpecified;
        
        private string colleagueIdField;
        
        private string colleagueNameField;
        
        private string colleaguebackgroundField;
        
        private long companyIdField;
        
        private string currentProjectField;
        
        private string defaultLanguageField;
        
        private string dialectIdField;
        
        private string ecmVersionField;
        
        private bool emailHtmlField;
        
        private bool emailHtmlFieldSpecified;
        
        private string especializationAreaField;
        
        private string extensionNrField;
        
        private bool gedUserField;
        
        private bool gedUserFieldSpecified;
        
        private string groupIdField;
        
        private bool guestUserField;
        
        private bool guestUserFieldSpecified;
        
        private string homePageField;
        
        private string loginField;
        
        private string mailField;
        
        private float maxPrivateSizeField;
        
        private bool maxPrivateSizeFieldSpecified;
        
        private int menuConfigField;
        
        private bool menuConfigFieldSpecified;
        
        private bool nominalUserField;
        
        private bool nominalUserFieldSpecified;
        
        private string passwdField;
        
        private string photoPathField;
        
        private int rowIdField;
        
        private string sessionIdField;
        
        private float usedSpaceField;
        
        private bool usedSpaceFieldSpecified;
        
        private string volumeIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
                this.RaisePropertyChanged("active");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activeSpecified {
            get {
                return this.activeFieldSpecified;
            }
            set {
                this.activeFieldSpecified = value;
                this.RaisePropertyChanged("activeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool adminUser {
            get {
                return this.adminUserField;
            }
            set {
                this.adminUserField = value;
                this.RaisePropertyChanged("adminUser");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool adminUserSpecified {
            get {
                return this.adminUserFieldSpecified;
            }
            set {
                this.adminUserFieldSpecified = value;
                this.RaisePropertyChanged("adminUserSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int area1Id {
            get {
                return this.area1IdField;
            }
            set {
                this.area1IdField = value;
                this.RaisePropertyChanged("area1Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool area1IdSpecified {
            get {
                return this.area1IdFieldSpecified;
            }
            set {
                this.area1IdFieldSpecified = value;
                this.RaisePropertyChanged("area1IdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int area2Id {
            get {
                return this.area2IdField;
            }
            set {
                this.area2IdField = value;
                this.RaisePropertyChanged("area2Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool area2IdSpecified {
            get {
                return this.area2IdFieldSpecified;
            }
            set {
                this.area2IdFieldSpecified = value;
                this.RaisePropertyChanged("area2IdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int area3Id {
            get {
                return this.area3IdField;
            }
            set {
                this.area3IdField = value;
                this.RaisePropertyChanged("area3Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool area3IdSpecified {
            get {
                return this.area3IdFieldSpecified;
            }
            set {
                this.area3IdFieldSpecified = value;
                this.RaisePropertyChanged("area3IdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int area4Id {
            get {
                return this.area4IdField;
            }
            set {
                this.area4IdField = value;
                this.RaisePropertyChanged("area4Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool area4IdSpecified {
            get {
                return this.area4IdFieldSpecified;
            }
            set {
                this.area4IdFieldSpecified = value;
                this.RaisePropertyChanged("area4IdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int area5Id {
            get {
                return this.area5IdField;
            }
            set {
                this.area5IdField = value;
                this.RaisePropertyChanged("area5Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool area5IdSpecified {
            get {
                return this.area5IdFieldSpecified;
            }
            set {
                this.area5IdFieldSpecified = value;
                this.RaisePropertyChanged("area5IdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string colleagueId {
            get {
                return this.colleagueIdField;
            }
            set {
                this.colleagueIdField = value;
                this.RaisePropertyChanged("colleagueId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string colleagueName {
            get {
                return this.colleagueNameField;
            }
            set {
                this.colleagueNameField = value;
                this.RaisePropertyChanged("colleagueName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string colleaguebackground {
            get {
                return this.colleaguebackgroundField;
            }
            set {
                this.colleaguebackgroundField = value;
                this.RaisePropertyChanged("colleaguebackground");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public long companyId {
            get {
                return this.companyIdField;
            }
            set {
                this.companyIdField = value;
                this.RaisePropertyChanged("companyId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string currentProject {
            get {
                return this.currentProjectField;
            }
            set {
                this.currentProjectField = value;
                this.RaisePropertyChanged("currentProject");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string defaultLanguage {
            get {
                return this.defaultLanguageField;
            }
            set {
                this.defaultLanguageField = value;
                this.RaisePropertyChanged("defaultLanguage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string dialectId {
            get {
                return this.dialectIdField;
            }
            set {
                this.dialectIdField = value;
                this.RaisePropertyChanged("dialectId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string ecmVersion {
            get {
                return this.ecmVersionField;
            }
            set {
                this.ecmVersionField = value;
                this.RaisePropertyChanged("ecmVersion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public bool emailHtml {
            get {
                return this.emailHtmlField;
            }
            set {
                this.emailHtmlField = value;
                this.RaisePropertyChanged("emailHtml");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool emailHtmlSpecified {
            get {
                return this.emailHtmlFieldSpecified;
            }
            set {
                this.emailHtmlFieldSpecified = value;
                this.RaisePropertyChanged("emailHtmlSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string especializationArea {
            get {
                return this.especializationAreaField;
            }
            set {
                this.especializationAreaField = value;
                this.RaisePropertyChanged("especializationArea");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string extensionNr {
            get {
                return this.extensionNrField;
            }
            set {
                this.extensionNrField = value;
                this.RaisePropertyChanged("extensionNr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public bool gedUser {
            get {
                return this.gedUserField;
            }
            set {
                this.gedUserField = value;
                this.RaisePropertyChanged("gedUser");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool gedUserSpecified {
            get {
                return this.gedUserFieldSpecified;
            }
            set {
                this.gedUserFieldSpecified = value;
                this.RaisePropertyChanged("gedUserSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string groupId {
            get {
                return this.groupIdField;
            }
            set {
                this.groupIdField = value;
                this.RaisePropertyChanged("groupId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public bool guestUser {
            get {
                return this.guestUserField;
            }
            set {
                this.guestUserField = value;
                this.RaisePropertyChanged("guestUser");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool guestUserSpecified {
            get {
                return this.guestUserFieldSpecified;
            }
            set {
                this.guestUserFieldSpecified = value;
                this.RaisePropertyChanged("guestUserSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string homePage {
            get {
                return this.homePageField;
            }
            set {
                this.homePageField = value;
                this.RaisePropertyChanged("homePage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
                this.RaisePropertyChanged("login");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string mail {
            get {
                return this.mailField;
            }
            set {
                this.mailField = value;
                this.RaisePropertyChanged("mail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public float maxPrivateSize {
            get {
                return this.maxPrivateSizeField;
            }
            set {
                this.maxPrivateSizeField = value;
                this.RaisePropertyChanged("maxPrivateSize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maxPrivateSizeSpecified {
            get {
                return this.maxPrivateSizeFieldSpecified;
            }
            set {
                this.maxPrivateSizeFieldSpecified = value;
                this.RaisePropertyChanged("maxPrivateSizeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public int menuConfig {
            get {
                return this.menuConfigField;
            }
            set {
                this.menuConfigField = value;
                this.RaisePropertyChanged("menuConfig");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool menuConfigSpecified {
            get {
                return this.menuConfigFieldSpecified;
            }
            set {
                this.menuConfigFieldSpecified = value;
                this.RaisePropertyChanged("menuConfigSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public bool nominalUser {
            get {
                return this.nominalUserField;
            }
            set {
                this.nominalUserField = value;
                this.RaisePropertyChanged("nominalUser");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool nominalUserSpecified {
            get {
                return this.nominalUserFieldSpecified;
            }
            set {
                this.nominalUserFieldSpecified = value;
                this.RaisePropertyChanged("nominalUserSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public string passwd {
            get {
                return this.passwdField;
            }
            set {
                this.passwdField = value;
                this.RaisePropertyChanged("passwd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=28)]
        public string photoPath {
            get {
                return this.photoPathField;
            }
            set {
                this.photoPathField = value;
                this.RaisePropertyChanged("photoPath");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=29)]
        public int rowId {
            get {
                return this.rowIdField;
            }
            set {
                this.rowIdField = value;
                this.RaisePropertyChanged("rowId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=30)]
        public string sessionId {
            get {
                return this.sessionIdField;
            }
            set {
                this.sessionIdField = value;
                this.RaisePropertyChanged("sessionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=31)]
        public float usedSpace {
            get {
                return this.usedSpaceField;
            }
            set {
                this.usedSpaceField = value;
                this.RaisePropertyChanged("usedSpace");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool usedSpaceSpecified {
            get {
                return this.usedSpaceFieldSpecified;
            }
            set {
                this.usedSpaceFieldSpecified = value;
                this.RaisePropertyChanged("usedSpaceSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=32)]
        public string volumeId {
            get {
                return this.volumeIdField;
            }
            set {
                this.volumeIdField = value;
                this.RaisePropertyChanged("volumeId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.foundation.ecm.technology.totvs.com/", ConfigurationName="FluigColleagueService.ColleagueService")]
    public interface ColleagueService {
        
        // CODEGEN: O parâmetro 'result' requer informações adicionais de esquema que não podem ser capturadas usando o modo do parâmetro. O atributo específico é 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="getColleaguesMail", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(AtualizadorMatriculas.FluigColleagueService.Exception), Action="getColleaguesMail", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        AtualizadorMatriculas.FluigColleagueService.getColleaguesMailResponse getColleaguesMail(AtualizadorMatriculas.FluigColleagueService.getColleaguesMail request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getColleaguesMail", ReplyAction="*")]
        System.Threading.Tasks.Task<AtualizadorMatriculas.FluigColleagueService.getColleaguesMailResponse> getColleaguesMailAsync(AtualizadorMatriculas.FluigColleagueService.getColleaguesMail request);
        
        [System.ServiceModel.OperationContractAttribute(Action="removeColleague", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        string removeColleague(string username, string password, int companyId, string colleagueId);
        
        [System.ServiceModel.OperationContractAttribute(Action="removeColleague", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        System.Threading.Tasks.Task<string> removeColleagueAsync(string username, string password, int companyId, string colleagueId);
        
        // CODEGEN: O parâmetro 'result' requer informações adicionais de esquema que não podem ser capturadas usando o modo do parâmetro. O atributo específico é 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="getSummaryColleagues", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(AtualizadorMatriculas.FluigColleagueService.Exception), Action="getSummaryColleagues", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        AtualizadorMatriculas.FluigColleagueService.getSummaryColleaguesResponse getSummaryColleagues(AtualizadorMatriculas.FluigColleagueService.getSummaryColleagues request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getSummaryColleagues", ReplyAction="*")]
        System.Threading.Tasks.Task<AtualizadorMatriculas.FluigColleagueService.getSummaryColleaguesResponse> getSummaryColleaguesAsync(AtualizadorMatriculas.FluigColleagueService.getSummaryColleagues request);
        
        [System.ServiceModel.OperationContractAttribute(Action="validateColleagueLogin", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(AtualizadorMatriculas.FluigColleagueService.Exception), Action="validateColleagueLogin", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        string validateColleagueLogin(int companyId, string colleagueId, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="validateColleagueLogin", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        System.Threading.Tasks.Task<string> validateColleagueLoginAsync(int companyId, string colleagueId, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="activateColleague", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        string activateColleague(string username, string password, int companyId, string colleagueId);
        
        [System.ServiceModel.OperationContractAttribute(Action="activateColleague", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        System.Threading.Tasks.Task<string> activateColleagueAsync(string username, string password, int companyId, string colleagueId);
        
        [System.ServiceModel.OperationContractAttribute(Action="getColleague", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(AtualizadorMatriculas.FluigColleagueService.Exception), Action="getColleague", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        AtualizadorMatriculas.FluigColleagueService.colleagueDto getSimpleColleague(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="getColleague", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        System.Threading.Tasks.Task<AtualizadorMatriculas.FluigColleagueService.colleagueDto> getSimpleColleagueAsync(string username, string password);
        
        // CODEGEN: O parâmetro 'colab' requer informações adicionais de esquema que não podem ser capturadas usando o modo do parâmetro. O atributo específico é 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="get Groups", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(AtualizadorMatriculas.FluigColleagueService.Exception), Action="get Groups", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="colab")]
        AtualizadorMatriculas.FluigColleagueService.getGroupsResponse getGroups(AtualizadorMatriculas.FluigColleagueService.getGroups request);
        
        [System.ServiceModel.OperationContractAttribute(Action="get Groups", ReplyAction="*")]
        System.Threading.Tasks.Task<AtualizadorMatriculas.FluigColleagueService.getGroupsResponse> getGroupsAsync(AtualizadorMatriculas.FluigColleagueService.getGroups request);
        
        // CODEGEN: O parâmetro 'colleagues' requer informações adicionais de esquema que não podem ser capturadas usando o modo do parâmetro. O atributo específico é 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="createCollegue", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(AtualizadorMatriculas.FluigColleagueService.Exception), Action="createCollegue", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="resultXML")]
        AtualizadorMatriculas.FluigColleagueService.createColleagueResponse createColleague(AtualizadorMatriculas.FluigColleagueService.createColleague request);
        
        [System.ServiceModel.OperationContractAttribute(Action="createCollegue", ReplyAction="*")]
        System.Threading.Tasks.Task<AtualizadorMatriculas.FluigColleagueService.createColleagueResponse> createColleagueAsync(AtualizadorMatriculas.FluigColleagueService.createColleague request);
        
        // CODEGEN: O parâmetro 'colleagues' requer informações adicionais de esquema que não podem ser capturadas usando o modo do parâmetro. O atributo específico é 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="updateColleague", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(AtualizadorMatriculas.FluigColleagueService.Exception), Action="updateColleague", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="resultXML")]
        AtualizadorMatriculas.FluigColleagueService.updateColleagueResponse updateColleague(AtualizadorMatriculas.FluigColleagueService.updateColleague request);
        
        [System.ServiceModel.OperationContractAttribute(Action="updateColleague", ReplyAction="*")]
        System.Threading.Tasks.Task<AtualizadorMatriculas.FluigColleagueService.updateColleagueResponse> updateColleagueAsync(AtualizadorMatriculas.FluigColleagueService.updateColleague request);
        
        // CODEGEN: O parâmetro 'colleagues' requer informações adicionais de esquema que não podem ser capturadas usando o modo do parâmetro. O atributo específico é 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="createColleaguewithDependencies", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="resultXML")]
        AtualizadorMatriculas.FluigColleagueService.createColleaguewithDependenciesResponse createColleaguewithDependencies(AtualizadorMatriculas.FluigColleagueService.createColleaguewithDependencies request);
        
        [System.ServiceModel.OperationContractAttribute(Action="createColleaguewithDependencies", ReplyAction="*")]
        System.Threading.Tasks.Task<AtualizadorMatriculas.FluigColleagueService.createColleaguewithDependenciesResponse> createColleaguewithDependenciesAsync(AtualizadorMatriculas.FluigColleagueService.createColleaguewithDependencies request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getColleagueByLogin", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(AtualizadorMatriculas.FluigColleagueService.Exception), Action="getColleagueByLogin", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="colleagueId")]
        AtualizadorMatriculas.FluigColleagueService.colleagueDto getColleagueByLogin(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="getColleagueByLogin", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="colleagueId")]
        System.Threading.Tasks.Task<AtualizadorMatriculas.FluigColleagueService.colleagueDto> getColleagueByLoginAsync(string username, string password);
        
        // CODEGEN: O parâmetro 'result' requer informações adicionais de esquema que não podem ser capturadas usando o modo do parâmetro. O atributo específico é 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="getColleaguesCompressedData", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(AtualizadorMatriculas.FluigColleagueService.Exception), Action="getColleaguesCompressedData", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        AtualizadorMatriculas.FluigColleagueService.getColleaguesCompressedDataResponse getColleaguesCompressedData(AtualizadorMatriculas.FluigColleagueService.getColleaguesCompressedData request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getColleaguesCompressedData", ReplyAction="*")]
        System.Threading.Tasks.Task<AtualizadorMatriculas.FluigColleagueService.getColleaguesCompressedDataResponse> getColleaguesCompressedDataAsync(AtualizadorMatriculas.FluigColleagueService.getColleaguesCompressedData request);
        
        // CODEGEN: O parâmetro 'result' requer informações adicionais de esquema que não podem ser capturadas usando o modo do parâmetro. O atributo específico é 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="getColleagues", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(AtualizadorMatriculas.FluigColleagueService.Exception), Action="getColleagues", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        AtualizadorMatriculas.FluigColleagueService.getColleaguesResponse getColleagues(AtualizadorMatriculas.FluigColleagueService.getColleagues request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getColleagues", ReplyAction="*")]
        System.Threading.Tasks.Task<AtualizadorMatriculas.FluigColleagueService.getColleaguesResponse> getColleaguesAsync(AtualizadorMatriculas.FluigColleagueService.getColleagues request);
        
        // CODEGEN: O parâmetro 'colleagues' requer informações adicionais de esquema que não podem ser capturadas usando o modo do parâmetro. O atributo específico é 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="updateColleaguewithDependencies", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(AtualizadorMatriculas.FluigColleagueService.Exception), Action="updateColleaguewithDependencies", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="resultXML")]
        AtualizadorMatriculas.FluigColleagueService.updateColleaguewithDependenciesResponse updateColleaguewithDependencies(AtualizadorMatriculas.FluigColleagueService.updateColleaguewithDependencies request);
        
        [System.ServiceModel.OperationContractAttribute(Action="updateColleaguewithDependencies", ReplyAction="*")]
        System.Threading.Tasks.Task<AtualizadorMatriculas.FluigColleagueService.updateColleaguewithDependenciesResponse> updateColleaguewithDependenciesAsync(AtualizadorMatriculas.FluigColleagueService.updateColleaguewithDependencies request);
        
        [System.ServiceModel.OperationContractAttribute(Action="createColleagueWithMap", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="resultXML")]
        string createColleagueWithMap(string username, string password, string colleagueXML);
        
        [System.ServiceModel.OperationContractAttribute(Action="createColleagueWithMap", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="resultXML")]
        System.Threading.Tasks.Task<string> createColleagueWithMapAsync(string username, string password, string colleagueXML);
        
        // CODEGEN: O parâmetro 'colab' requer informações adicionais de esquema que não podem ser capturadas usando o modo do parâmetro. O atributo específico é 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="getColleague", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(AtualizadorMatriculas.FluigColleagueService.Exception), Action="getColleague", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="colab")]
        AtualizadorMatriculas.FluigColleagueService.getColleagueResponse getColleague(AtualizadorMatriculas.FluigColleagueService.getColleague request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getColleague", ReplyAction="*")]
        System.Threading.Tasks.Task<AtualizadorMatriculas.FluigColleagueService.getColleagueResponse> getColleagueAsync(AtualizadorMatriculas.FluigColleagueService.getColleague request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getColleaguesMail", WrapperNamespace="http://ws.foundation.ecm.technology.totvs.com/", IsWrapped=true)]
    public partial class getColleaguesMail {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public int companyId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string mail;
        
        public getColleaguesMail() {
        }
        
        public getColleaguesMail(string username, string password, int companyId, string mail) {
            this.username = username;
            this.password = password;
            this.companyId = companyId;
            this.mail = mail;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getColleaguesMailResponse", WrapperNamespace="http://ws.foundation.ecm.technology.totvs.com/", IsWrapped=true)]
    public partial class getColleaguesMailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute()]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AtualizadorMatriculas.FluigColleagueService.colleagueDto[] result;
        
        public getColleaguesMailResponse() {
        }
        
        public getColleaguesMailResponse(AtualizadorMatriculas.FluigColleagueService.colleagueDto[] result) {
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSummaryColleagues", WrapperNamespace="http://ws.foundation.ecm.technology.totvs.com/", IsWrapped=true)]
    public partial class getSummaryColleagues {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int companyId;
        
        public getSummaryColleagues() {
        }
        
        public getSummaryColleagues(int companyId) {
            this.companyId = companyId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSummaryColleaguesResponse", WrapperNamespace="http://ws.foundation.ecm.technology.totvs.com/", IsWrapped=true)]
    public partial class getSummaryColleaguesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute()]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AtualizadorMatriculas.FluigColleagueService.colleagueDto[] result;
        
        public getSummaryColleaguesResponse() {
        }
        
        public getSummaryColleaguesResponse(AtualizadorMatriculas.FluigColleagueService.colleagueDto[] result) {
            this.result = result;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.foundation.ecm.technology.totvs.com/")]
    public partial class groupDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long companyIdField;
        
        private string[] fooField;
        
        private string groupDescriptionField;
        
        private string groupIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long companyId {
            get {
                return this.companyIdField;
            }
            set {
                this.companyIdField = value;
                this.RaisePropertyChanged("companyId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("foo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string[] foo {
            get {
                return this.fooField;
            }
            set {
                this.fooField = value;
                this.RaisePropertyChanged("foo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string groupDescription {
            get {
                return this.groupDescriptionField;
            }
            set {
                this.groupDescriptionField = value;
                this.RaisePropertyChanged("groupDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string groupId {
            get {
                return this.groupIdField;
            }
            set {
                this.groupIdField = value;
                this.RaisePropertyChanged("groupId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getGroups", WrapperNamespace="http://ws.foundation.ecm.technology.totvs.com/", IsWrapped=true)]
    public partial class getGroups {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public int companyId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string colleagueId;
        
        public getGroups() {
        }
        
        public getGroups(string username, string password, int companyId, string colleagueId) {
            this.username = username;
            this.password = password;
            this.companyId = companyId;
            this.colleagueId = colleagueId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getGroupsResponse", WrapperNamespace="http://ws.foundation.ecm.technology.totvs.com/", IsWrapped=true)]
    public partial class getGroupsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute()]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AtualizadorMatriculas.FluigColleagueService.groupDto[] colab;
        
        public getGroupsResponse() {
        }
        
        public getGroupsResponse(AtualizadorMatriculas.FluigColleagueService.groupDto[] colab) {
            this.colab = colab;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createColleague", WrapperNamespace="http://ws.foundation.ecm.technology.totvs.com/", IsWrapped=true)]
    public partial class createColleague {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public int companyId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        [System.Xml.Serialization.XmlArrayAttribute()]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AtualizadorMatriculas.FluigColleagueService.colleagueDto[] colleagues;
        
        public createColleague() {
        }
        
        public createColleague(string username, string password, int companyId, AtualizadorMatriculas.FluigColleagueService.colleagueDto[] colleagues) {
            this.username = username;
            this.password = password;
            this.companyId = companyId;
            this.colleagues = colleagues;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createColleagueResponse", WrapperNamespace="http://ws.foundation.ecm.technology.totvs.com/", IsWrapped=true)]
    public partial class createColleagueResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string resultXML;
        
        public createColleagueResponse() {
        }
        
        public createColleagueResponse(string resultXML) {
            this.resultXML = resultXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateColleague", WrapperNamespace="http://ws.foundation.ecm.technology.totvs.com/", IsWrapped=true)]
    public partial class updateColleague {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public int companyId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        [System.Xml.Serialization.XmlArrayAttribute()]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AtualizadorMatriculas.FluigColleagueService.colleagueDto[] colleagues;
        
        public updateColleague() {
        }
        
        public updateColleague(string username, string password, int companyId, AtualizadorMatriculas.FluigColleagueService.colleagueDto[] colleagues) {
            this.username = username;
            this.password = password;
            this.companyId = companyId;
            this.colleagues = colleagues;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateColleagueResponse", WrapperNamespace="http://ws.foundation.ecm.technology.totvs.com/", IsWrapped=true)]
    public partial class updateColleagueResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string resultXML;
        
        public updateColleagueResponse() {
        }
        
        public updateColleagueResponse(string resultXML) {
            this.resultXML = resultXML;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.foundation.ecm.technology.totvs.com/")]
    public partial class workflowRoleDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long companyIdField;
        
        private string[] fooField;
        
        private string roleDescriptionField;
        
        private string roleIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long companyId {
            get {
                return this.companyIdField;
            }
            set {
                this.companyIdField = value;
                this.RaisePropertyChanged("companyId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("foo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string[] foo {
            get {
                return this.fooField;
            }
            set {
                this.fooField = value;
                this.RaisePropertyChanged("foo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string roleDescription {
            get {
                return this.roleDescriptionField;
            }
            set {
                this.roleDescriptionField = value;
                this.RaisePropertyChanged("roleDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string roleId {
            get {
                return this.roleIdField;
            }
            set {
                this.roleIdField = value;
                this.RaisePropertyChanged("roleId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createColleaguewithDependencies", WrapperNamespace="http://ws.foundation.ecm.technology.totvs.com/", IsWrapped=true)]
    public partial class createColleaguewithDependencies {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public int companyId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        [System.Xml.Serialization.XmlArrayAttribute()]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AtualizadorMatriculas.FluigColleagueService.colleagueDto[] colleagues;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        [System.Xml.Serialization.XmlArrayAttribute()]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AtualizadorMatriculas.FluigColleagueService.groupDto[] groups;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        [System.Xml.Serialization.XmlArrayAttribute()]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AtualizadorMatriculas.FluigColleagueService.workflowRoleDto[] workflowRoles;
        
        public createColleaguewithDependencies() {
        }
        
        public createColleaguewithDependencies(string username, string password, int companyId, AtualizadorMatriculas.FluigColleagueService.colleagueDto[] colleagues, AtualizadorMatriculas.FluigColleagueService.groupDto[] groups, AtualizadorMatriculas.FluigColleagueService.workflowRoleDto[] workflowRoles) {
            this.username = username;
            this.password = password;
            this.companyId = companyId;
            this.colleagues = colleagues;
            this.groups = groups;
            this.workflowRoles = workflowRoles;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createColleaguewithDependenciesResponse", WrapperNamespace="http://ws.foundation.ecm.technology.totvs.com/", IsWrapped=true)]
    public partial class createColleaguewithDependenciesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string resultXML;
        
        public createColleaguewithDependenciesResponse() {
        }
        
        public createColleaguewithDependenciesResponse(string resultXML) {
            this.resultXML = resultXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getColleaguesCompressedData", WrapperNamespace="http://ws.foundation.ecm.technology.totvs.com/", IsWrapped=true)]
    public partial class getColleaguesCompressedData {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public int companyId;
        
        public getColleaguesCompressedData() {
        }
        
        public getColleaguesCompressedData(string username, string password, int companyId) {
            this.username = username;
            this.password = password;
            this.companyId = companyId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getColleaguesCompressedDataResponse", WrapperNamespace="http://ws.foundation.ecm.technology.totvs.com/", IsWrapped=true)]
    public partial class getColleaguesCompressedDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] result;
        
        public getColleaguesCompressedDataResponse() {
        }
        
        public getColleaguesCompressedDataResponse(byte[] result) {
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getColleagues", WrapperNamespace="http://ws.foundation.ecm.technology.totvs.com/", IsWrapped=true)]
    public partial class getColleagues {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public int companyId;
        
        public getColleagues() {
        }
        
        public getColleagues(string username, string password, int companyId) {
            this.username = username;
            this.password = password;
            this.companyId = companyId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getColleaguesResponse", WrapperNamespace="http://ws.foundation.ecm.technology.totvs.com/", IsWrapped=true)]
    public partial class getColleaguesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute()]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AtualizadorMatriculas.FluigColleagueService.colleagueDto[] result;
        
        public getColleaguesResponse() {
        }
        
        public getColleaguesResponse(AtualizadorMatriculas.FluigColleagueService.colleagueDto[] result) {
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateColleaguewithDependencies", WrapperNamespace="http://ws.foundation.ecm.technology.totvs.com/", IsWrapped=true)]
    public partial class updateColleaguewithDependencies {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public int companyId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        [System.Xml.Serialization.XmlArrayAttribute()]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AtualizadorMatriculas.FluigColleagueService.colleagueDto[] colleagues;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        [System.Xml.Serialization.XmlArrayAttribute()]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AtualizadorMatriculas.FluigColleagueService.groupDto[] groups;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        [System.Xml.Serialization.XmlArrayAttribute()]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AtualizadorMatriculas.FluigColleagueService.workflowRoleDto[] workflowRoles;
        
        public updateColleaguewithDependencies() {
        }
        
        public updateColleaguewithDependencies(string username, string password, int companyId, AtualizadorMatriculas.FluigColleagueService.colleagueDto[] colleagues, AtualizadorMatriculas.FluigColleagueService.groupDto[] groups, AtualizadorMatriculas.FluigColleagueService.workflowRoleDto[] workflowRoles) {
            this.username = username;
            this.password = password;
            this.companyId = companyId;
            this.colleagues = colleagues;
            this.groups = groups;
            this.workflowRoles = workflowRoles;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateColleaguewithDependenciesResponse", WrapperNamespace="http://ws.foundation.ecm.technology.totvs.com/", IsWrapped=true)]
    public partial class updateColleaguewithDependenciesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string resultXML;
        
        public updateColleaguewithDependenciesResponse() {
        }
        
        public updateColleaguewithDependenciesResponse(string resultXML) {
            this.resultXML = resultXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getColleague", WrapperNamespace="http://ws.foundation.ecm.technology.totvs.com/", IsWrapped=true)]
    public partial class getColleague {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public int companyId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string colleagueId;
        
        public getColleague() {
        }
        
        public getColleague(string username, string password, int companyId, string colleagueId) {
            this.username = username;
            this.password = password;
            this.companyId = companyId;
            this.colleagueId = colleagueId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getColleagueResponse", WrapperNamespace="http://ws.foundation.ecm.technology.totvs.com/", IsWrapped=true)]
    public partial class getColleagueResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute()]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AtualizadorMatriculas.FluigColleagueService.colleagueDto[] colab;
        
        public getColleagueResponse() {
        }
        
        public getColleagueResponse(AtualizadorMatriculas.FluigColleagueService.colleagueDto[] colab) {
            this.colab = colab;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ColleagueServiceChannel : AtualizadorMatriculas.FluigColleagueService.ColleagueService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ColleagueServiceClient : System.ServiceModel.ClientBase<AtualizadorMatriculas.FluigColleagueService.ColleagueService>, AtualizadorMatriculas.FluigColleagueService.ColleagueService {
        
        public ColleagueServiceClient() {
        }
        
        public ColleagueServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ColleagueServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ColleagueServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ColleagueServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AtualizadorMatriculas.FluigColleagueService.getColleaguesMailResponse AtualizadorMatriculas.FluigColleagueService.ColleagueService.getColleaguesMail(AtualizadorMatriculas.FluigColleagueService.getColleaguesMail request) {
            return base.Channel.getColleaguesMail(request);
        }
        
        public AtualizadorMatriculas.FluigColleagueService.colleagueDto[] getColleaguesMail(string username, string password, int companyId, string mail) {
            AtualizadorMatriculas.FluigColleagueService.getColleaguesMail inValue = new AtualizadorMatriculas.FluigColleagueService.getColleaguesMail();
            inValue.username = username;
            inValue.password = password;
            inValue.companyId = companyId;
            inValue.mail = mail;
            AtualizadorMatriculas.FluigColleagueService.getColleaguesMailResponse retVal = ((AtualizadorMatriculas.FluigColleagueService.ColleagueService)(this)).getColleaguesMail(inValue);
            return retVal.result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AtualizadorMatriculas.FluigColleagueService.getColleaguesMailResponse> AtualizadorMatriculas.FluigColleagueService.ColleagueService.getColleaguesMailAsync(AtualizadorMatriculas.FluigColleagueService.getColleaguesMail request) {
            return base.Channel.getColleaguesMailAsync(request);
        }
        
        public System.Threading.Tasks.Task<AtualizadorMatriculas.FluigColleagueService.getColleaguesMailResponse> getColleaguesMailAsync(string username, string password, int companyId, string mail) {
            AtualizadorMatriculas.FluigColleagueService.getColleaguesMail inValue = new AtualizadorMatriculas.FluigColleagueService.getColleaguesMail();
            inValue.username = username;
            inValue.password = password;
            inValue.companyId = companyId;
            inValue.mail = mail;
            return ((AtualizadorMatriculas.FluigColleagueService.ColleagueService)(this)).getColleaguesMailAsync(inValue);
        }
        
        public string removeColleague(string username, string password, int companyId, string colleagueId) {
            return base.Channel.removeColleague(username, password, companyId, colleagueId);
        }
        
        public System.Threading.Tasks.Task<string> removeColleagueAsync(string username, string password, int companyId, string colleagueId) {
            return base.Channel.removeColleagueAsync(username, password, companyId, colleagueId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AtualizadorMatriculas.FluigColleagueService.getSummaryColleaguesResponse AtualizadorMatriculas.FluigColleagueService.ColleagueService.getSummaryColleagues(AtualizadorMatriculas.FluigColleagueService.getSummaryColleagues request) {
            return base.Channel.getSummaryColleagues(request);
        }
        
        public AtualizadorMatriculas.FluigColleagueService.colleagueDto[] getSummaryColleagues(int companyId) {
            AtualizadorMatriculas.FluigColleagueService.getSummaryColleagues inValue = new AtualizadorMatriculas.FluigColleagueService.getSummaryColleagues();
            inValue.companyId = companyId;
            AtualizadorMatriculas.FluigColleagueService.getSummaryColleaguesResponse retVal = ((AtualizadorMatriculas.FluigColleagueService.ColleagueService)(this)).getSummaryColleagues(inValue);
            return retVal.result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AtualizadorMatriculas.FluigColleagueService.getSummaryColleaguesResponse> AtualizadorMatriculas.FluigColleagueService.ColleagueService.getSummaryColleaguesAsync(AtualizadorMatriculas.FluigColleagueService.getSummaryColleagues request) {
            return base.Channel.getSummaryColleaguesAsync(request);
        }
        
        public System.Threading.Tasks.Task<AtualizadorMatriculas.FluigColleagueService.getSummaryColleaguesResponse> getSummaryColleaguesAsync(int companyId) {
            AtualizadorMatriculas.FluigColleagueService.getSummaryColleagues inValue = new AtualizadorMatriculas.FluigColleagueService.getSummaryColleagues();
            inValue.companyId = companyId;
            return ((AtualizadorMatriculas.FluigColleagueService.ColleagueService)(this)).getSummaryColleaguesAsync(inValue);
        }
        
        public string validateColleagueLogin(int companyId, string colleagueId, string password) {
            return base.Channel.validateColleagueLogin(companyId, colleagueId, password);
        }
        
        public System.Threading.Tasks.Task<string> validateColleagueLoginAsync(int companyId, string colleagueId, string password) {
            return base.Channel.validateColleagueLoginAsync(companyId, colleagueId, password);
        }
        
        public string activateColleague(string username, string password, int companyId, string colleagueId) {
            return base.Channel.activateColleague(username, password, companyId, colleagueId);
        }
        
        public System.Threading.Tasks.Task<string> activateColleagueAsync(string username, string password, int companyId, string colleagueId) {
            return base.Channel.activateColleagueAsync(username, password, companyId, colleagueId);
        }
        
        public AtualizadorMatriculas.FluigColleagueService.colleagueDto getSimpleColleague(string username, string password) {
            return base.Channel.getSimpleColleague(username, password);
        }
        
        public System.Threading.Tasks.Task<AtualizadorMatriculas.FluigColleagueService.colleagueDto> getSimpleColleagueAsync(string username, string password) {
            return base.Channel.getSimpleColleagueAsync(username, password);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AtualizadorMatriculas.FluigColleagueService.getGroupsResponse AtualizadorMatriculas.FluigColleagueService.ColleagueService.getGroups(AtualizadorMatriculas.FluigColleagueService.getGroups request) {
            return base.Channel.getGroups(request);
        }
        
        public AtualizadorMatriculas.FluigColleagueService.groupDto[] getGroups(string username, string password, int companyId, string colleagueId) {
            AtualizadorMatriculas.FluigColleagueService.getGroups inValue = new AtualizadorMatriculas.FluigColleagueService.getGroups();
            inValue.username = username;
            inValue.password = password;
            inValue.companyId = companyId;
            inValue.colleagueId = colleagueId;
            AtualizadorMatriculas.FluigColleagueService.getGroupsResponse retVal = ((AtualizadorMatriculas.FluigColleagueService.ColleagueService)(this)).getGroups(inValue);
            return retVal.colab;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AtualizadorMatriculas.FluigColleagueService.getGroupsResponse> AtualizadorMatriculas.FluigColleagueService.ColleagueService.getGroupsAsync(AtualizadorMatriculas.FluigColleagueService.getGroups request) {
            return base.Channel.getGroupsAsync(request);
        }
        
        public System.Threading.Tasks.Task<AtualizadorMatriculas.FluigColleagueService.getGroupsResponse> getGroupsAsync(string username, string password, int companyId, string colleagueId) {
            AtualizadorMatriculas.FluigColleagueService.getGroups inValue = new AtualizadorMatriculas.FluigColleagueService.getGroups();
            inValue.username = username;
            inValue.password = password;
            inValue.companyId = companyId;
            inValue.colleagueId = colleagueId;
            return ((AtualizadorMatriculas.FluigColleagueService.ColleagueService)(this)).getGroupsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AtualizadorMatriculas.FluigColleagueService.createColleagueResponse AtualizadorMatriculas.FluigColleagueService.ColleagueService.createColleague(AtualizadorMatriculas.FluigColleagueService.createColleague request) {
            return base.Channel.createColleague(request);
        }
        
        public string createColleague(string username, string password, int companyId, AtualizadorMatriculas.FluigColleagueService.colleagueDto[] colleagues) {
            AtualizadorMatriculas.FluigColleagueService.createColleague inValue = new AtualizadorMatriculas.FluigColleagueService.createColleague();
            inValue.username = username;
            inValue.password = password;
            inValue.companyId = companyId;
            inValue.colleagues = colleagues;
            AtualizadorMatriculas.FluigColleagueService.createColleagueResponse retVal = ((AtualizadorMatriculas.FluigColleagueService.ColleagueService)(this)).createColleague(inValue);
            return retVal.resultXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AtualizadorMatriculas.FluigColleagueService.createColleagueResponse> AtualizadorMatriculas.FluigColleagueService.ColleagueService.createColleagueAsync(AtualizadorMatriculas.FluigColleagueService.createColleague request) {
            return base.Channel.createColleagueAsync(request);
        }
        
        public System.Threading.Tasks.Task<AtualizadorMatriculas.FluigColleagueService.createColleagueResponse> createColleagueAsync(string username, string password, int companyId, AtualizadorMatriculas.FluigColleagueService.colleagueDto[] colleagues) {
            AtualizadorMatriculas.FluigColleagueService.createColleague inValue = new AtualizadorMatriculas.FluigColleagueService.createColleague();
            inValue.username = username;
            inValue.password = password;
            inValue.companyId = companyId;
            inValue.colleagues = colleagues;
            return ((AtualizadorMatriculas.FluigColleagueService.ColleagueService)(this)).createColleagueAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AtualizadorMatriculas.FluigColleagueService.updateColleagueResponse AtualizadorMatriculas.FluigColleagueService.ColleagueService.updateColleague(AtualizadorMatriculas.FluigColleagueService.updateColleague request) {
            return base.Channel.updateColleague(request);
        }
        
        public string updateColleague(string username, string password, int companyId, AtualizadorMatriculas.FluigColleagueService.colleagueDto[] colleagues) {
            AtualizadorMatriculas.FluigColleagueService.updateColleague inValue = new AtualizadorMatriculas.FluigColleagueService.updateColleague();
            inValue.username = username;
            inValue.password = password;
            inValue.companyId = companyId;
            inValue.colleagues = colleagues;
            AtualizadorMatriculas.FluigColleagueService.updateColleagueResponse retVal = ((AtualizadorMatriculas.FluigColleagueService.ColleagueService)(this)).updateColleague(inValue);
            return retVal.resultXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AtualizadorMatriculas.FluigColleagueService.updateColleagueResponse> AtualizadorMatriculas.FluigColleagueService.ColleagueService.updateColleagueAsync(AtualizadorMatriculas.FluigColleagueService.updateColleague request) {
            return base.Channel.updateColleagueAsync(request);
        }
        
        public System.Threading.Tasks.Task<AtualizadorMatriculas.FluigColleagueService.updateColleagueResponse> updateColleagueAsync(string username, string password, int companyId, AtualizadorMatriculas.FluigColleagueService.colleagueDto[] colleagues) {
            AtualizadorMatriculas.FluigColleagueService.updateColleague inValue = new AtualizadorMatriculas.FluigColleagueService.updateColleague();
            inValue.username = username;
            inValue.password = password;
            inValue.companyId = companyId;
            inValue.colleagues = colleagues;
            return ((AtualizadorMatriculas.FluigColleagueService.ColleagueService)(this)).updateColleagueAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AtualizadorMatriculas.FluigColleagueService.createColleaguewithDependenciesResponse AtualizadorMatriculas.FluigColleagueService.ColleagueService.createColleaguewithDependencies(AtualizadorMatriculas.FluigColleagueService.createColleaguewithDependencies request) {
            return base.Channel.createColleaguewithDependencies(request);
        }
        
        public string createColleaguewithDependencies(string username, string password, int companyId, AtualizadorMatriculas.FluigColleagueService.colleagueDto[] colleagues, AtualizadorMatriculas.FluigColleagueService.groupDto[] groups, AtualizadorMatriculas.FluigColleagueService.workflowRoleDto[] workflowRoles) {
            AtualizadorMatriculas.FluigColleagueService.createColleaguewithDependencies inValue = new AtualizadorMatriculas.FluigColleagueService.createColleaguewithDependencies();
            inValue.username = username;
            inValue.password = password;
            inValue.companyId = companyId;
            inValue.colleagues = colleagues;
            inValue.groups = groups;
            inValue.workflowRoles = workflowRoles;
            AtualizadorMatriculas.FluigColleagueService.createColleaguewithDependenciesResponse retVal = ((AtualizadorMatriculas.FluigColleagueService.ColleagueService)(this)).createColleaguewithDependencies(inValue);
            return retVal.resultXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AtualizadorMatriculas.FluigColleagueService.createColleaguewithDependenciesResponse> AtualizadorMatriculas.FluigColleagueService.ColleagueService.createColleaguewithDependenciesAsync(AtualizadorMatriculas.FluigColleagueService.createColleaguewithDependencies request) {
            return base.Channel.createColleaguewithDependenciesAsync(request);
        }
        
        public System.Threading.Tasks.Task<AtualizadorMatriculas.FluigColleagueService.createColleaguewithDependenciesResponse> createColleaguewithDependenciesAsync(string username, string password, int companyId, AtualizadorMatriculas.FluigColleagueService.colleagueDto[] colleagues, AtualizadorMatriculas.FluigColleagueService.groupDto[] groups, AtualizadorMatriculas.FluigColleagueService.workflowRoleDto[] workflowRoles) {
            AtualizadorMatriculas.FluigColleagueService.createColleaguewithDependencies inValue = new AtualizadorMatriculas.FluigColleagueService.createColleaguewithDependencies();
            inValue.username = username;
            inValue.password = password;
            inValue.companyId = companyId;
            inValue.colleagues = colleagues;
            inValue.groups = groups;
            inValue.workflowRoles = workflowRoles;
            return ((AtualizadorMatriculas.FluigColleagueService.ColleagueService)(this)).createColleaguewithDependenciesAsync(inValue);
        }
        
        public AtualizadorMatriculas.FluigColleagueService.colleagueDto getColleagueByLogin(string username, string password) {
            return base.Channel.getColleagueByLogin(username, password);
        }
        
        public System.Threading.Tasks.Task<AtualizadorMatriculas.FluigColleagueService.colleagueDto> getColleagueByLoginAsync(string username, string password) {
            return base.Channel.getColleagueByLoginAsync(username, password);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AtualizadorMatriculas.FluigColleagueService.getColleaguesCompressedDataResponse AtualizadorMatriculas.FluigColleagueService.ColleagueService.getColleaguesCompressedData(AtualizadorMatriculas.FluigColleagueService.getColleaguesCompressedData request) {
            return base.Channel.getColleaguesCompressedData(request);
        }
        
        public byte[] getColleaguesCompressedData(string username, string password, int companyId) {
            AtualizadorMatriculas.FluigColleagueService.getColleaguesCompressedData inValue = new AtualizadorMatriculas.FluigColleagueService.getColleaguesCompressedData();
            inValue.username = username;
            inValue.password = password;
            inValue.companyId = companyId;
            AtualizadorMatriculas.FluigColleagueService.getColleaguesCompressedDataResponse retVal = ((AtualizadorMatriculas.FluigColleagueService.ColleagueService)(this)).getColleaguesCompressedData(inValue);
            return retVal.result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AtualizadorMatriculas.FluigColleagueService.getColleaguesCompressedDataResponse> AtualizadorMatriculas.FluigColleagueService.ColleagueService.getColleaguesCompressedDataAsync(AtualizadorMatriculas.FluigColleagueService.getColleaguesCompressedData request) {
            return base.Channel.getColleaguesCompressedDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<AtualizadorMatriculas.FluigColleagueService.getColleaguesCompressedDataResponse> getColleaguesCompressedDataAsync(string username, string password, int companyId) {
            AtualizadorMatriculas.FluigColleagueService.getColleaguesCompressedData inValue = new AtualizadorMatriculas.FluigColleagueService.getColleaguesCompressedData();
            inValue.username = username;
            inValue.password = password;
            inValue.companyId = companyId;
            return ((AtualizadorMatriculas.FluigColleagueService.ColleagueService)(this)).getColleaguesCompressedDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AtualizadorMatriculas.FluigColleagueService.getColleaguesResponse AtualizadorMatriculas.FluigColleagueService.ColleagueService.getColleagues(AtualizadorMatriculas.FluigColleagueService.getColleagues request) {
            return base.Channel.getColleagues(request);
        }
        
        public AtualizadorMatriculas.FluigColleagueService.colleagueDto[] getColleagues(string username, string password, int companyId) {
            AtualizadorMatriculas.FluigColleagueService.getColleagues inValue = new AtualizadorMatriculas.FluigColleagueService.getColleagues();
            inValue.username = username;
            inValue.password = password;
            inValue.companyId = companyId;
            AtualizadorMatriculas.FluigColleagueService.getColleaguesResponse retVal = ((AtualizadorMatriculas.FluigColleagueService.ColleagueService)(this)).getColleagues(inValue);
            return retVal.result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AtualizadorMatriculas.FluigColleagueService.getColleaguesResponse> AtualizadorMatriculas.FluigColleagueService.ColleagueService.getColleaguesAsync(AtualizadorMatriculas.FluigColleagueService.getColleagues request) {
            return base.Channel.getColleaguesAsync(request);
        }
        
        public System.Threading.Tasks.Task<AtualizadorMatriculas.FluigColleagueService.getColleaguesResponse> getColleaguesAsync(string username, string password, int companyId) {
            AtualizadorMatriculas.FluigColleagueService.getColleagues inValue = new AtualizadorMatriculas.FluigColleagueService.getColleagues();
            inValue.username = username;
            inValue.password = password;
            inValue.companyId = companyId;
            return ((AtualizadorMatriculas.FluigColleagueService.ColleagueService)(this)).getColleaguesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AtualizadorMatriculas.FluigColleagueService.updateColleaguewithDependenciesResponse AtualizadorMatriculas.FluigColleagueService.ColleagueService.updateColleaguewithDependencies(AtualizadorMatriculas.FluigColleagueService.updateColleaguewithDependencies request) {
            return base.Channel.updateColleaguewithDependencies(request);
        }
        
        public string updateColleaguewithDependencies(string username, string password, int companyId, AtualizadorMatriculas.FluigColleagueService.colleagueDto[] colleagues, AtualizadorMatriculas.FluigColleagueService.groupDto[] groups, AtualizadorMatriculas.FluigColleagueService.workflowRoleDto[] workflowRoles) {
            AtualizadorMatriculas.FluigColleagueService.updateColleaguewithDependencies inValue = new AtualizadorMatriculas.FluigColleagueService.updateColleaguewithDependencies();
            inValue.username = username;
            inValue.password = password;
            inValue.companyId = companyId;
            inValue.colleagues = colleagues;
            inValue.groups = groups;
            inValue.workflowRoles = workflowRoles;
            AtualizadorMatriculas.FluigColleagueService.updateColleaguewithDependenciesResponse retVal = ((AtualizadorMatriculas.FluigColleagueService.ColleagueService)(this)).updateColleaguewithDependencies(inValue);
            return retVal.resultXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AtualizadorMatriculas.FluigColleagueService.updateColleaguewithDependenciesResponse> AtualizadorMatriculas.FluigColleagueService.ColleagueService.updateColleaguewithDependenciesAsync(AtualizadorMatriculas.FluigColleagueService.updateColleaguewithDependencies request) {
            return base.Channel.updateColleaguewithDependenciesAsync(request);
        }
        
        public System.Threading.Tasks.Task<AtualizadorMatriculas.FluigColleagueService.updateColleaguewithDependenciesResponse> updateColleaguewithDependenciesAsync(string username, string password, int companyId, AtualizadorMatriculas.FluigColleagueService.colleagueDto[] colleagues, AtualizadorMatriculas.FluigColleagueService.groupDto[] groups, AtualizadorMatriculas.FluigColleagueService.workflowRoleDto[] workflowRoles) {
            AtualizadorMatriculas.FluigColleagueService.updateColleaguewithDependencies inValue = new AtualizadorMatriculas.FluigColleagueService.updateColleaguewithDependencies();
            inValue.username = username;
            inValue.password = password;
            inValue.companyId = companyId;
            inValue.colleagues = colleagues;
            inValue.groups = groups;
            inValue.workflowRoles = workflowRoles;
            return ((AtualizadorMatriculas.FluigColleagueService.ColleagueService)(this)).updateColleaguewithDependenciesAsync(inValue);
        }
        
        public string createColleagueWithMap(string username, string password, string colleagueXML) {
            return base.Channel.createColleagueWithMap(username, password, colleagueXML);
        }
        
        public System.Threading.Tasks.Task<string> createColleagueWithMapAsync(string username, string password, string colleagueXML) {
            return base.Channel.createColleagueWithMapAsync(username, password, colleagueXML);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AtualizadorMatriculas.FluigColleagueService.getColleagueResponse AtualizadorMatriculas.FluigColleagueService.ColleagueService.getColleague(AtualizadorMatriculas.FluigColleagueService.getColleague request) {
            return base.Channel.getColleague(request);
        }
        
        public AtualizadorMatriculas.FluigColleagueService.colleagueDto[] getColleague(string username, string password, int companyId, string colleagueId) {
            AtualizadorMatriculas.FluigColleagueService.getColleague inValue = new AtualizadorMatriculas.FluigColleagueService.getColleague();
            inValue.username = username;
            inValue.password = password;
            inValue.companyId = companyId;
            inValue.colleagueId = colleagueId;
            AtualizadorMatriculas.FluigColleagueService.getColleagueResponse retVal = ((AtualizadorMatriculas.FluigColleagueService.ColleagueService)(this)).getColleague(inValue);
            return retVal.colab;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AtualizadorMatriculas.FluigColleagueService.getColleagueResponse> AtualizadorMatriculas.FluigColleagueService.ColleagueService.getColleagueAsync(AtualizadorMatriculas.FluigColleagueService.getColleague request) {
            return base.Channel.getColleagueAsync(request);
        }
        
        public System.Threading.Tasks.Task<AtualizadorMatriculas.FluigColleagueService.getColleagueResponse> getColleagueAsync(string username, string password, int companyId, string colleagueId) {
            AtualizadorMatriculas.FluigColleagueService.getColleague inValue = new AtualizadorMatriculas.FluigColleagueService.getColleague();
            inValue.username = username;
            inValue.password = password;
            inValue.companyId = companyId;
            inValue.colleagueId = colleagueId;
            return ((AtualizadorMatriculas.FluigColleagueService.ColleagueService)(this)).getColleagueAsync(inValue);
        }
    }
}
